### ISSUE TITLE
android 12 support

### ISSUE THREAD

**Issue by soredake** [ph4n70m-404/DocumentsUI-Replacer#1]
Would be nice to have android 12 support, right now both apks don't work, they just crash.

**Comment by ph4n70m-404** [comment]
Yeah I'm guessing the apks are version specific. I'll probably add support for a12 somewhat soonish.

**Comment by ph4n70m-404** [comment]
I believe this is now fixed in v3

**Comment by soredake** [comment]
Unfortunately it crashes on crdroid 8.4, log https://paste.crdroid.net/dBNfvV

**Comment by ph4n70m-404** [comment]
Can you send the magisk log while its installing?

**Comment by soredake** [comment]
[magisk_install_log_2022-05-29T20_13_49.zip](https://github.com/ph4n70m-404/DocumentsUI-Replacer/files/8793869/magisk_install_log_2022-05-29T20_13_49.zip)
